name: Maven CI

on:
  push:
    branches: [ release ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      deployments: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          server-id: github
          distribution: adopt
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Test dir
        run: dir
      - name: Build & Package
        run: |
          mvn -B package --file pom.xml
          mkdir build && cp SimpliFX/target/*.jar build && cp DemoApplications/target/*.jar build && cp Doku/Bachelorarbeit.pdf build && cp ReflectionUtils/target/*.jar build && cp SimpliFX-Dagger1/target/*.jar build && cp SimpliFX-Guice/target/*.jar build && cp SimpliFX-Spring/target/*.jar build
      - name: Cache setup
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml')}}
          restore-keys: ${{runner.os}}-m2
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts as release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.*
          tag: ${{ github.ref }}
          file_glob: true
          release_name: SimpliFX & ReflectionUtils & Demo Application
      - name: Publish package
        run: mvn -B deploy -s settings.xml
        env:
          MVN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
